### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Qimie** [Qimie/AlwaysSpawn#1]
- [ ] Mention @NidPlays When All Of This Finished.

- [ ] Update plugin.yml.

- [ ] Make The Plugin Generates A Config File.

- [ ] Add SimpleAuth Support.

- [ ] Make Player Teleport To A Temporary Lobby When The Player Joined & Not Logged In.

- [ ] Make Player Teleport To A Lobby Or Map After He Logged In.

- [ ] Makes The Plugin Check If SimpleAuth 

- [ ] Makes The Plugin Disable The New Feature Above If There Is No SimpleAuth Installed.

- [ ] Update README.md

**Comment by NidPlays** [comment]
Cool
